/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EpicNFTs } from "./EpicNFTs";

export { EpicNFTs__factory } from "./factories/EpicNFTs__factory";
